version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.example
    environment:
      PORT: ${APP_PORT}
      ENV: ${APP_ENV}
      FILL: ${APP_FILL}
      MIGRATIONS: ${APP_MIGRATIONS}
      DSN: ${APP_DSN}
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Set the database name here
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"  # Changed the host port to avoid conflict if you have another PostgreSQL instance
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
